### ISSUE TITLE
facing Daylight issue for some countires

### ISSUE THREAD

**Issue by sagarveer444** [mattjohnsonpint/TimeZoneNames#90] opened 2023-02-16 08:56 UTC
We are facing daylight issues for some countries (Colombia, and Brazil Sao/Paulo) where the library is returning standard timezone as 'null' and daylight value as true.

Used Version: 6.0.0

**Comment by mattjohnsonpint** [comment] 2023-02-16 21:12
Can you provide an example in code please?

**Comment by sagarveer444** [comment] 2023-02-17 06:57
![image](https://user-images.githubusercontent.com/28435897/219570671-6474162a-818d-4ee4-966f-f6e1fd0a5844.png)

From above code 
abbreviations.Standard is assigned to strabbreviations variable, which is null.
on other hand abbreviations.Daylight returning timezone as "COST"
and Hosttimelocal.IsDaylightSavingTime(convertedDatetime) is returning **FALSE**
**userTimezone = "America/Bogota"** i.e. Colombia (America/Bogota) UTC -05:00

**Comment by mattjohnsonpint** [comment] 2023-02-17 21:37
This is an issue with abbreviations only.  The following is a minimal repro:

```csharp
var abbreviations = TZNames.GetAbbreviationsForTimeZone("America/Bogota", "en-US");
Console.WriteLine("Generic: " + abbreviations.Generic);
Console.WriteLine("Standard: " + abbreviations.Standard);
Console.WriteLine("Daylight: " + abbreviations.Daylight);
```

Output:
```
Generic: 
Standard: 
Daylight: COST
```

Works fine for names though:

```csharp
var names = TZNames.GetNamesForTimeZone("America/Bogota", "en-US");
Console.WriteLine("Generic: " + names.Generic);
Console.WriteLine("Standard: " + names.Standard);
Console.WriteLine("Daylight: " + names.Daylight);
```

Output:
```
Generic: Colombia Time
Standard: Colombia Standard Time
Daylight: Colombia Summer Time
```

**Comment by mattjohnsonpint** [comment] 2023-02-17 22:15
A big part of the problem is that time zone abbreviations are unreliable in the CLDR data.

In the example case, the cause is that CLDR only has one English abbreviation for Colombia, and it's for daylight time.

https://github.com/unicode-org/cldr/blob/main/common/main/en_CA.xml#L4629

I need to rethink how time zone abbreviations work in general.  We have plenty of other issues with them.  I haven't decided yet, but I may just remove them completely.

**Comment by sagarveer444** [comment] 2023-02-20 08:26
> This is an issue with abbreviations only. The following is a minimal repro:
> 
> ```cs
> var abbreviations = TZNames.GetAbbreviationsForTimeZone("America/Bogota", "en-US");
> Console.WriteLine("Generic: " + abbreviations.Generic);
> Console.WriteLine("Standard: " + abbreviations.Standard);
> Console.WriteLine("Daylight: " + abbreviations.Daylight);
> ```
> 
> Output:
> 
> ```
> Generic: 
> Standard: 
> Daylight: COST
> ```
> 
> Works fine for names though:
> 
> ```cs
> var names = TZNames.GetNamesForTimeZone("America/Bogota", "en-US");
> Console.WriteLine("Generic: " + names.Generic);
> Console.WriteLine("Standard: " + names.Standard);
> Console.WriteLine("Daylight: " + names.Daylight);
> ```
> 
> Output:
> 
> ```
> Generic: Colombia Time
> Standard: Colombia Standard Time
> Daylight: Colombia Summer Time
> ```

@mattjohnsonpint  Thanks its worked for me..👍

**Comment by mattjohnsonpint** [comment] 2023-03-07 00:30
Closing.  Will track abbreviations issue in #91.  Thanks.

**Closed by mattjohnsonpint** 2023-03-07 00:30 UTC
Labels: bug
